package main

// The wasi:* bindings in internal/ are generated by the official Bytecode Alliance generator
// from TinyGo's own WIT files; to regenerate:
//
//go:generate sh -c "go run go.bytecodealliance.org/cmd/wit-bindgen-go@v0.7.0 generate --world wasi:cli/command --out internal --package-root wshell.example/hello-go/internal $(tinygo env TINYGOROOT)/lib/wasi-cli/wit"
